### PR TITLE
Merging Federico's site into this one

### PR DESCRIPTION
**Pull request by dblotsky**
- Added two new pages: `benchmarks.md` and `syntax.md`
- Added two Makefile targets, `bench` and `plot`, to run the new scripts
- Now generating a `-model` copy (which has a `(get-model)` line) of each instance

### CODE REVIEW

**Comment by dblotsky** [comment]
@FedericoAureliano please give this a look.

**Comment by FedericoAureliano** [comment]
When I try to make the problems or build I get 

```
python3 bin/make_problems.py problems site/_data/problems.yml
Traceback (most recent call last):
  File "bin/make_problems.py", line 117, in <module>
    main()
  File "bin/make_problems.py", line 66, in main
    for suite in config:
TypeError: 'NoneType' object is not iterable
Makefile:102: recipe for target 'problems' failed
make: *** [problems] Error 1
```

**Comment by FedericoAureliano** [comment]
Also, any chance we can get the makefile to install some of the solver or grab the latest version of Murphy's Z3? Also it would be really cool if running bench would put in the specs of the computer that the experiments were run on. OK, now i'm just getting greedy

**Comment by dblotsky** [comment]
@FedericoAureliano I’ll answer in order:
1. I want to consider not generating the get-model ones at all. I think the tester can do that automatically. The problem generator can’t always be sure if some instances are sat.
2. The path to the results can be relative or absolute. It gets passed as the destination of a symlink.
3. What do you mean by setting up results and problems? The Makefile automatically generates the problems for things that depend on them.
4. I’ll look into the error you’re seeing.
5. I have the solver-installing stuff and my own graph making stuff, but it’s not in this repo. I can give you access to that too, but it shouldn’t be in this repo, IMO. I think we should ultimately move bench and plot out of this repo. What do you think?

**Comment by FedericoAureliano** [comment]
Hey @dblotsky. I totally agree with 1, I just put those in for an experiment a few weeks ago. As for 5 I personally would put all that stuff in here. I can't see myself ever using these scripts in a different context. Also it just seems convenient. Otherwise access to the other repo would be great!

**Comment by dblotsky** [comment]
@FedericoAureliano 
1. I've given you access to the other repo.
2. The error you're seeing shouldn't be happening. Can you please run `make nuke`, and then re-run `make build`? If you still see an error, please paste the whole output, and I'll investigate further.

**Pull request merged**
